1 dimensional array in numpy

In [ ]:
import numpy as np
array_1d = np.array([1,2,3,4,5,6,7,8,9])
array_1d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
list_1d = [1,2,3,4,5,6,7,8,9]
list_1d

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
type(array_id)

numpy.ndarray

In [5]:
type(list_id)

list

2 dimensional array

In [8]:
array_2d = np.array([[1,2,3,4],[5,6,7,8]])
array_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
array_3d = np.array([[1,2,3],[4,5,6],[7,8,9]])
array_3d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
zeros_array = np.zeros((2,3))
zeros_array

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
# Array attributes
print("Shape:", array_2d.shape)  # Expected Output: Shape: (2, 3) - 2 rows and 3 columns
print("Size:", array_2d.size)   # Expected Output: Size: 6 - Total 6 elements
print("Data Type:", array_2d.dtype)  # Expected Output: Data Type: int64 (or similar, depending on system)

Shape: (2, 4)
Size: 8
Data Type: int64



# Data Type: Description
- int: 	Integer (e.g., int16, int32, int64)
- float:	Floating-point number (e.g., float16, float32, float64)
- bool:	Boolean (True or False)
- complex:	Complex number (e.g., complex64, complex128)
- str:	String
- object:	Python object type

# Reshaping Arrays for Analysis


In [13]:
import numpy as np

# Creating a 1D array
array = np.arange(1, 10)  # Array of numbers from 1 to 9

# Reshaping to a 3x3 matrix
reshaped_array = array.reshape(3, 3)
print("Reshaped to 3x3:\n", reshaped_array)

Reshaped to 3x3:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
array_flat = reshaped_array.flatten()
array_flat 

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
array_weekly_sales = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
array_week = array_weekly_sales.reshape(-1,7)
array_week

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [18]:
array_weekly_sales = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
array_week = array_weekly_sales.reshape(-1,7)
array_week

ValueError: cannot reshape array of size 16 into shape (7)

In [27]:
array_weekly_sales = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
array_week = array_weekly_sales.reshape(3,-1)
array_week

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [28]:
array_weekly_sales = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
array_weekly_sales.resize(2,3)
array_weekly_sales

array([[1, 2, 3],
       [4, 5, 6]])

Practice:

In [44]:
temps = np.array([30, 32, 31, 29, 28, 27, 26, 25, 24, 26, 28, 30, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,41, 42, 43, 44, 45, 46, 47, 48])
temps2 = np.array([30, 32, 31, 29, 28, 27, 26, 25, 24, 26, 28, 30, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,32,46,21])
week_temps = temps2.reshape(-1,7)
week_temps

array([[30, 32, 31, 29, 28, 27, 26],
       [25, 24, 26, 28, 30, 29, 30],
       [31, 32, 33, 34, 35, 36, 37],
       [38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 32, 46, 21]])

In [47]:
temps3 = np.array([30, 32, 31, 29, 28, 27, 26, 25, 24, 26, 28, 30, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 4])
temps3.size

31

In [37]:
week_temps.shape

(4, 8)

In [35]:
week_temps.resize(4, 8)
week_temps

array([[30, 32, 31, 29, 28, 27, 26, 25],
       [24, 26, 28, 30, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48]])

In [48]:
import numpy as np

# Example array
array = np.array([[1, 2], [3, 4], [5, 6]])

# Boolean indexing
result = array[array > 3]
print("Result of Boolean Indexing:", result)  # Output: [4 5 6], a 1D array


import numpy as np

# Creating a sample array
array = np.array([10, 20, 30, 40, 50])

# Indexing (accessing a single element)
print("First element:", array[0])

# Slicing (accessing multiple elements)
print("First three elements:", array[:3])

Result of Boolean Indexing: [4 5 6]
First element: 10
First three elements: [10 20 30]


In [55]:
import pandas as pd
import numpy as np
# Create the sales data as a pandas DataFrame
sales_data = pd.DataFrame({
    "Monday": [200, 150, 100, 300, 50],
    "Tuesday": [220, 160, 110, 320, 60],
    "Wednesday": [250, 180, 120, 340, 70],
    "Thursday": [270, 200, 130, 360, 80],
    "Friday": [300, 210, 140, 400, 90],
    "Saturday": [310, 220, 150, 420, 100],
    "Sunday": [280, 190, 160, 410, 110]
}, index=["Store 1", "Store 2", "Store 3", "Store 4", "Store 5"])
print("Sales Data (Pandas DataFrame):\n", sales_data)

Sales Data (Pandas DataFrame):
          Monday  Tuesday  Wednesday  Thursday  Friday  Saturday  Sunday
Store 1     200      220        250       270     300       310     280
Store 2     150      160        180       200     210       220     190
Store 3     100      110        120       130     140       150     160
Store 4     300      320        340       360     400       420     410
Store 5      50       60         70        80      90       100     110


In [56]:
sales_data2 = sales_data.to_numpy()
sales_data2

array([[200, 220, 250, 270, 300, 310, 280],
       [150, 160, 180, 200, 210, 220, 190],
       [100, 110, 120, 130, 140, 150, 160],
       [300, 320, 340, 360, 400, 420, 410],
       [ 50,  60,  70,  80,  90, 100, 110]])

In [64]:
store_4 = sales_data2[3, :]
store_4

array([300, 320, 340, 360, 400, 420, 410])

# AND/OR for finding where store 4 sales is greater than 4

In [68]:
store_4 = sales_data2[3,sales_data2[3]>350]
store_4


array([360, 400, 420, 410])

In [66]:
store_4_above_350 = np.where(store_4>350)
print(store_4_above_350[0]+1)

[4 5 6 7]


In [71]:
day_names = sales_data.columns[store_4_above_350].tolist()
day_names

['Thursday', 'Friday', 'Saturday', 'Sunday']