🌟 Exercise 1 : Array Creation and Manipulation
Instructions
Create a 1D NumPy array containing numbers from 0 to 9.

🌟 Exercise 2 : Type Conversion and Array Operations
Instructions
Convert a list [3.14, 2.17, 0, 1, 2] into a NumPy array and convert its data type to integer.

🌟 Exercise 3 : Working with Multi-Dimensional Arrays
Instructions
Create a 3x3 NumPy array with values ranging from 1 to 9.

🌟 Exercise 4 : Creating Multi-Dimensional Array with Random Numbers
Instructions
Create a 2D NumPy array of shape (4, 5) filled with random numbers.

🌟 Exercise 5 : Indexing Arrays
Instructions
Select the second row from a given 2D NumPy array.

🌟 Exercise 6 : Reversing elements
Instructions
Reverse the order of elements in a given 1D NumPy array (first element becomes last).

🌟 Exercise 7 : Identity Matrix
Instructions
Create a 4x4 identity matrix using NumPy.

🌟 Exercise 8 : Simple Aggregate Funcs
Instructions
Find the sum and average of a given 1D array.

🌟 Exercise 9 : Create Array and Change its Structure
Instructions
Create a NumPy array with elements from 1 to 20; then reshape it into a 4x5 matrix.

🌟 Exercise 10 : Conditional Selection of Values
Instructions
Extract all odd numbers from a given NumPy array.

In [1]:
# 🌟 Exercise 1 
import numpy as np
array_1d = np.array([0,1,2,3,4,5,6,7,8,9])
array_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
import numpy as np
# 🌟 Exercise 2
# Convert a list [3.14, 2.17, 0, 1, 2] into a NumPy array and convert its data type to integer.
array = np.array([3.14, 2.17, 0, 1, 2])
array_int = array.astype(int)
array_int

array([3, 2, 0, 1, 2])

In [4]:
# 🌟 Exercise 3
# Create a 3x3 NumPy array with values ranging from 1 to 9.
import numpy as np
array = np.arange(1,10).reshape(3,3)
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
# 🌟 Exercise 4
# Create a 2D NumPy array of shape (4, 5) filled with random numbers.
import numpy as np
array2d = np.random.randint(1, 100, size=(4, 5))
array2d

array([[80, 82, 46, 50, 92],
       [68, 27, 43, 45, 78],
       [59, 18, 53, 44, 17],
       [11, 83, 74, 54,  1]])

In [9]:
array2d2 = np.random.rand(4, 5)
array2d2

array([[0.39016135, 0.05542366, 0.17001299, 0.42180746, 0.0492106 ],
       [0.16351694, 0.35340349, 0.48987982, 0.99605093, 0.08564334],
       [0.37746876, 0.21743896, 0.43321449, 0.62629419, 0.10603985],
       [0.68905893, 0.64632795, 0.10295038, 0.4522847 , 0.48834951]])

In [10]:
# 🌟 Exercise 5
# Select the second row from a given 2D NumPy array.

array = np.array([[21,22,23,22,22],[20, 21, 22, 23, 24],[21,22,23,22,22]])
array[1,:]

array([20, 21, 22, 23, 24])

In [ ]:
# 🌟 Exercise 6
# Reverse the order of elements in a given 1D NumPy array (first element becomes last).
A = np.array([21,22,23,22,22])
np.flip(A, 0)


array([22, 22, 23, 22, 21])

In [24]:
# 🌟 Exercise 7
# Create a 4x4 identity matrix using NumPy.
Array = np.identity(4)
Array

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
# 🌟 Exercise 8
# Find the sum and average of a given 1D array.
array_1d = np.array([0,1,2,3,4,5,6,7,8,9])
np.sum(array_1d)
np.mean(array_1d)

np.float64(4.5)

In [28]:
# 🌟 Exercise 9
# Create a NumPy array with elements from 1 to 20; then reshape it into a 4x5 matrix.
import numpy as np
Array = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
Array2 = Array.reshape(4,5)
Array2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
# 🌟 Exercise 10
# Extract all odd numbers from a given NumPy array.
Array = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
Array[Array % 2 != 0]


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])